MANJIT SINGH T117

PRACTICAL NO 3A

AIM - Feature Scaling and Dummification:

 Apply feature-scaling techniques like standardization and normalization to
numerical features.

 Perform feature dummification to convert categorical variables into numerical
representations.

HANDLING NUMERICAL DATA

Rescaling a feature

MinMaxScaler

In [1]:
import numpy as np
from sklearn import preprocessing

feature =np.array([
    [-1000.5],
    [-200.1],
    [0],
    [200.1],
    [800.9]
    ])
minmax_scaler = preprocessing.MinMaxScaler(feature_range=(0,1))
scaled_feature = minmax_scaler.fit_transform(feature)
scaled_feature

array([[0.        ],
       [0.44432108],
       [0.55540135],
       [0.66648163],
       [1.        ]])

Using Dataset

In [3]:
import pandas as pd
from sklearn import preprocessing
df = pd.read_csv('Employee.csv')
feature = df['Age']

feature = feature.values.reshape(-1, 1)
minmax_scaler = preprocessing.MinMaxScaler(feature_range=(0,1))
scaled_feature = minmax_scaler.fit_transform(feature)
scaled_feature
# Slice the array to get the first 5 elements
sliced_array = scaled_feature[:5]
# Print the sliced array
print(sliced_array)

[[0.63157895]
 [0.31578947]
 [0.84210526]
 [0.26315789]
 [0.10526316]]


Standardizing a Feature

In [4]:
import numpy as np
from sklearn import preprocessing
scaler = preprocessing. StandardScaler()
standardized = scaler.fit_transform(feature)
feature=np.array([
    [-1000.1],
    [-500.2],
    [800.5],
    [500.6],
    [9000.9]])
print("Mean {}".format(round (standardized.mean())))
print("Standard deviation: {}".format(standardized.std()))

Mean 0
Standard deviation: 1.0


using the RobustScaler method:

In [5]:
robust_scaler = preprocessing.RobustScaler()
robust_scaler.fit_transform(feature)

array([[-1.15376336],
       [-0.76943184],
       [ 0.23056816],
       [ 0.        ],
       [ 6.53517337]])

Standardscalar Using Dataset


In [7]:
import pandas as pd
from sklearn import preprocessing
scaler = preprocessing. StandardScaler()

df = pd.read_csv('Employee.csv')
feature = df['PaymentTier']
feature =np.array(feature).reshape(-1, 1)

standardized = scaler.fit_transform(feature)
print("Mean {}".format(round (standardized.mean())))
print("Standard deviation: {}".format(standardized.std()))

Mean 0
Standard deviation: 1.0


using the RobustScaler method:using dataset

In [8]:
robust_scaler = preprocessing.RobustScaler()
robust_scaler.fit_transform(feature)
transformed_feature = robust_scaler.transform(feature)

# Slice the transformed data
sliced_array = transformed_feature[:5]

# Print the sliced array
print(sliced_array)

[[ 0.]
 [-2.]
 [ 0.]
 [ 0.]
 [ 0.]]


Normalizing Observations

In [9]:
import numpy as np
from sklearn.preprocessing import Normalizer
features = np.array([
    [0.8,0.2],
    [1.1,3.9],
    [2.7,50.2],
    [3.63,35.4],
    [11.9,4.3],
])
normalizerl1=Normalizer(norm="l1")
normalizerl2=Normalizer(norm="l2")
normalizerMax=Normalizer(norm="max")
print("l1 normalization\n",normalizerl1.transform(features))
print("\nl2 normalization\n",normalizerl2.transform(features))
print("\nmax normalization\n",normalizerMax.transform(features))

l1 normalization
 [[0.8        0.2       ]
 [0.22       0.78      ]
 [0.0510397  0.9489603 ]
 [0.09300538 0.90699462]
 [0.7345679  0.2654321 ]]

l2 normalization
 [[0.9701425  0.24253563]
 [0.27146017 0.96244968]
 [0.05370723 0.99855672]
 [0.10200747 0.99478363]
 [0.94048375 0.33983867]]

max normalization
 [[1.         0.25      ]
 [0.28205128 1.        ]
 [0.05378486 1.        ]
 [0.10254237 1.        ]
 [1.         0.36134454]]


Using Dataset

In [10]:
import pandas as pd
from sklearn.preprocessing import Normalizer

# Read the CSV file into a DataFrame
df = pd.read_csv('Employee.csv')

# Extract the 'PassengerId' column and reshape it for normalization
feature = df['Age']
feature = np.array(feature).reshape(-1, 1)

# Initialize Normalizers
normalizer_l1 = Normalizer(norm="l1")
normalizer_l2 = Normalizer(norm="l2")
normalizer_max = Normalizer(norm="max")

# Perform normalization
normalized_l1 = normalizer_l1.transform(feature)
normalized_l2 = normalizer_l2.transform(feature)
normalized_max = normalizer_max.transform(feature)

# Print a portion of the transformed data
print("l1 normalization\n", normalized_l1[:5])  # Printing first 5 rows
print("\nl2 normalization\n", normalized_l2[:5])  # Printing first 5 rows
print("\nmax normalization\n", normalized_max[:5])  # Printing first 5 rows


l1 normalization
 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]]

l2 normalization
 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]]

max normalization
 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


Grouping Observations Using Clustering

In [18]:
import pandas as pd
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans
features,_= make_blobs(n_samples = 50,
                     n_features=2,
                     centers=3,
                     random_state=1)
df=pd.DataFrame(features,columns=["feature_1","feature_2"])
clusterer=KMeans(3,random_state=0)
clusterer.fit(features)
df["group"]=clusterer.predict(features)
df.head()

feature_1  feature_2  group
0  -9.877554  -3.336145      2
1  -7.287210  -8.353986      0
2  -6.943061  -7.023744      0
3  -7.440167  -8.791959      0
4  -6.641388  -8.075888      0

Using Dataset

In [12]:
import pandas as pd
from sklearn.cluster import KMeans

# Read the CSV file into a DataFrame
df = pd.read_csv('Employee.csv')

# Extract the 'PassengerId' column and reshape it for clustering
features = df['Age']
features = np.array(features).reshape(-1, 1)

# Create a DataFrame with the features
df_features = pd.DataFrame(features, columns=["Age"])

# Initialize and fit KMeans clustering
clusterer = KMeans(n_clusters=3, random_state=0)
clusterer.fit(features)

# Add cluster labels to the DataFrame
df_features["group"] = clusterer.labels_

# Display the DataFrame with cluster labels
print(df_features.head())


   Age  group
0   34      1
1   28      0
2   38      1
3   27      0
4   24      2


Deleteing Observations with Missing Values


In [13]:
import numpy as np
features = np.array([
    [1.3,15.1],
    [3.2,25.6],
    [4.3,37.1],
    [np.nan,55]
])
features[~np.isnan(features).any(axis=1)]

array([[ 1.3, 15.1],
       [ 3.2, 25.6],
       [ 4.3, 37.1]])

Using Dataset


In [14]:
import pandas as pd


# Read the CSV file into a DataFrame
df = pd.read_csv('Employee.csv')

# Extract the 'PassengerId' column
features = df['Age']

# Reshape the feature for clustering
features = np.array(features).reshape(-1, 1)

# Remove rows with NaN values
features_cleaned = features[~np.isnan(features).any(axis=1)]

# Slice the cleaned features array to display a portion of it
portion_of_features = features_cleaned[:10]  # Displaying the first 10 rows

# Display the sliced portion of the cleaned features
print(portion_of_features)


[[34]
 [28]
 [38]
 [27]
 [24]
 [22]
 [38]
 [34]
 [23]
 [37]]


Imputing Missing Value

In [15]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.datasets import make_blobs

features, _ = make_blobs(n_samples=1000, n_features=2, random_state=1)

# standardize the features
scaler = StandardScaler()
standardized_features = scaler.fit_transform(features)

# replace the first feature's first value with a missing value
true_value = standardized_features[0, 0]
standardized_features[0, 0] = np.nan

# create imputer
mean_imputer = SimpleImputer(strategy="mean")
median_imputer = SimpleImputer(strategy="median")
mode_imputer = SimpleImputer(strategy="most_frequent")

# impute values
features_mean_imputed = mean_imputer.fit_transform(standardized_features)
features_median_imputed = median_imputer.fit_transform(standardized_features)
features_mode_imputed = mode_imputer.fit_transform(standardized_features)

# compare true and imputed values
print("True Value: {}".format(true_value))
print("Mean Imputed Value: {}".format(features_mean_imputed[0, 0]))
print("Median Imputed Value: {}".format(features_median_imputed[0, 0]))
print("Mode Imputed Value: {}".format(features_mode_imputed[0, 0]))

True Value: 0.8730186113995938
Mean Imputed Value: -0.000873892503901796
Median Imputed Value: -0.23980483042535553
Mode Imputed Value: -1.9059115647714258


Using Dataset

In [16]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

# Read the CSV file into a DataFrame
df = pd.read_csv('Employee.csv')

# Extract the 'PassengerId' column
features = df['Age']

# Reshape the feature for clustering
features = np.array(features).reshape(-1, 1)

# Apply imputation
# Create imputer
mean_imputer = SimpleImputer(strategy="mean")
median_imputer = SimpleImputer(strategy="median")
mode_imputer = SimpleImputer(strategy="most_frequent")

# Impute values
features_mean_imputed = mean_imputer.fit_transform(features)
features_median_imputed = median_imputer.fit_transform(features)
features_mode_imputed = mode_imputer.fit_transform(features)

# Compare true and imputed values for the first element
print("Mean Imputed Value: {}".format(features_mean_imputed[0, 0]))
print("Median Imputed Value: {}".format(features_median_imputed[0, 0]))
print("Mode Imputed Value: {}".format(features_mode_imputed[0, 0]))

Mean Imputed Value: 34.0
Median Imputed Value: 34.0
Mode Imputed Value: 34
